### ISSUE TITLE
No install instructions?

### ISSUE THREAD

**Issue by planux** [SanketKarpe/srujan#2]
I attended your session on Srujan at BlackHat earlier this year, and I've got some time to give it a try. I see a blank install instruction file. If you can give me a high-level description of how to install and run Srujan, I'm happy to put in a pull request with detailed instructions and screenshots for others to give it a try.

**Comment by SanketKarpe** [comment]
Hi,
I will be updating the INSTALL file in couple of days. Have been caught up with updating few core components and the install doc creation got pushed to end of queue.

**Comment by SanketKarpe** [comment]
Updated the install instructions. Will be adding script to auto install and configure required components
